### ISSUE TITLE
cLoops2 diff-background-MANormFit and diffLoopsMA plot interpretation

### ISSUE THREAD

**Issue by YuZhang337** [YaqiangCao/cLoops2#10]
Hi @YaqiangCao 
  thanks a lot for the wonderful software!
  I used cLoops2 callDiffLoops on two hichip data and it worked successfully. The specific command parameters are as follows：cLoops2 callDiffLoops -tloop HiC-540_loops.txt -td HiC-541 -cloop HiC-540_loops.txt -cd HiC-540 -o Diffloop. But the output made me confused, so I would like to ask for advice.
  diff_background_MANormFit shows that the number of up-regulated and down-regulated loops is similar, and the MA distribution is also normal. The results are as follows：
![image](https://github.com/YaqiangCao/cLoops2/assets/70937959/fe10526f-ad68-454f-9bd2-e25f7c164bff)
   However, diffLoopsMA shows that this is not the case. Most of them are down-regulated loops. The results are as follows：
![image](https://github.com/YaqiangCao/cLoops2/assets/70937959/e4b0e25c-2949-4e24-b95e-9524a01ff93b)
 I'm not sure about the specific reasons and whether the results are normal.Could you please give me some advice? I look forward to your reply.

**Comment by YaqiangCao** [comment]
Hi Yu, 
     Thank you for your interest of cLoops2. 
     Your results look pretty normal to me.  For the first figure, cLoops2 uses the ***nearby regions of true loops as background (bg)*** to estimate the difference between the two conditions, and it seems they are pretty similar. So indeed for true loops most of them are down-regulated. As your data are hichip, you can further check if there are significant signal decrease of these loop anchor regions from the same factor ChIP-seq data as an extra validation. 
      Let me know if you have more questions regarding this issue. 
Best,
Yaqiang
