### ISSUE TITLE
How can I convert pairtools output o BEDPE file as input of cLoops2?

### ISSUE THREAD

**Issue by hanshanmengqi** [YaqiangCao/cLoops2#13]
Hello @YaqiangCao,

Thank you for your helpful software.
I have a question: can I convert the pairtools output (More info: https://micro-c.readthedocs.io/en/latest/fastq_to_bam.html#gpb) into a BEDPE file for use as input in cLoops2?

Any comments or suggestions are welcome.

Han

**Comment by YaqiangCao** [comment]
> Hello @YaqiangCao,
> 
> Thank you for your helpful software. I have a question: can I convert the pairtools output (More info: https://micro-c.readthedocs.io/en/latest/fastq_to_bam.html#gpb) into a BEDPE file for use as input in cLoops2?
> 
> Any comments or suggestions are welcome.
> 
> Han

Hi @hanshanmengqi , 
     You can do that. Or just use cLoops2 pre with  -format pairs option if the output file of pairtools is .pairs file. 

cLoops2 pre supports input file formats:
BEDPE: https://bedtools.readthedocs.io/en/latest/content/general-usage.html 
PAIRS: https://pairtools.readthedocs.io/en/latest/formats.html#pairs 

     By the way, this option is added as suggested by the reviewers in 2021, thanks to them. 
Best,
Yaqiang

**Comment by hanshanmengqi** [comment]
Thank you so much for your swift response.

Best wishes,
Han
