### ISSUE TITLE
Few loops were detected by cLoops

### ISSUE THREAD

**Issue by hanshanmengqi** [YaqiangCao/cLoops2#14]
Hello @YaqiangCao,

Sorry to disturb you again.
I found that very few loops were detected by cLoops, which is quite different compared to when using Homer or FitHiC to call loops.

I am working with Hi-C data and have tried different parameters. My command is as follows:

"cLoops2 callLoops -d WT -o WT -eps 200,500,1000,2000,5000,10000 -minPts 20,50 -hic",  only 162 loops were detected.

However, when I changed **-minPts** to **5**, 9363 loops were detected.

I am wondering how I can choose the right parameters for my data.
Could you give me some suggestions?

Thank you.
Han

**Comment by YaqiangCao** [comment]
Hi Han, 
     I think your Hi-C may have limited reads? What's the observed resolution (estRes)? I would suggest -eps 5000,10000 -minPts 10, 20 for a initial run and then load the data into juicebox or washU to check the loops.  
Best,
Yaqiang 

> Hello @YaqiangCao,
> 
> Sorry to disturb you again. I found that very few loops were detected by cLoops, which is quite different compared to when using Homer or FitHiC to call loops.
> 
> I am working with Hi-C data and have tried different parameters. My command is as follows:
> 
> "cLoops2 callLoops -d WT -o WT -eps 200,500,1000,2000,5000,10000 -minPts 20,50 -hic", only 162 loops were detected.
> 
> However, when I changed **-minPts** to **5**, 9363 loops were detected.
> 
> I am wondering how I can choose the right parameters for my data. Could you give me some suggestions?
> 
> Thank you. Han
