### ISSUE TITLE
how to plot loops

### ISSUE THREAD

**Issue by ahmedabbas81** [YaqiangCao/cLoops2#4]
Hello,

I am trying to plot loops in a bedpe file.

I understand I should use the function `plot.plotLoops`

However, can you please give me an example on the parameter loops in the function. Is it a dataframe? Can you please point me to an example using this function with its available data?

Thanks

**Comment by YaqiangCao** [comment]
> Hello,
> 
> I am trying to plot loops in a bedpe file.
> 
> I understand I should use the function `plot.plotLoops`
> 
> However, can you please give me an example on the parameter loops in the function. Is it a dataframe? Can you please point me to an example using this function with its available data?
> 
> Thanks

Hi, 
    You can find example here: #show enhancer-promoter loops
cLoops2 plot -f gm/chr21-chr21.ixy -o gm_example -bs 500 -start 38752604 -end 38839334 -triu -bw ../data/GM12878_ATAC_chr21.bw,../data/GM12878_CTCF_chr21.bw -1D -loops gm_loops.txt -beds ../data/GM12878_RoadMap_hg38_Enh_chr21.bed,../data/GM12878_RoadMap_hg38_Tss_chr21.bed,gm_peaks.bed -m obs -log -gtf ../data/gencode_v30_chr21.gtf -vmax 1 
   https://github.com/YaqiangCao/cLoops2/raw/master/pngs/gm_example_matrix.png
   
   loops file: https://github.com/YaqiangCao/cLoops2/blob/master/example/test_run/gm_samp_loops.txt 

   loops file format: https://github.com/YaqiangCao/cLoops2#_loops.txt 
 
Best,
Yaqiang
