### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by poflawless** [YaqiangCao/cLoops2#6]
Hello Dr/Pro Gao,

When I tryied to use the command as below to call domain, cloops2 raised an error: **_IndexError: tuple index out of range_**
cLoops2 callDomains -d Pre_sample1_merge_sampled -o Pre_sample1_merge_sampled_Domain -bs 1000,5000 -ws 500,1000,5000 -p 12,

what can I do to correct it?

Thanks a lot for your help

**Comment by YaqiangCao** [comment]
Could you please share some of the test data? I am not sure about the
problem based on the current error. Thank you.

**Comment by poflawless** [comment]
Thanks Dr  Gao for your reply,   please download the file below which I analysed now.



 https://filesender.renater.fr/?s=download&token=cb323bc2-a831-4df2-acbc-9dbf7b94246f​



Best Wishes,

POFLAWLESS

**Comment by YaqiangCao** [comment]
Hi POFLAWLESS,
    Sorry for the late reply. I am quit busy recently.  It seems the link
is not valid that I can not access the test data. Do you still need the
help?
Best,
Yaqiang

**Comment by poflawless** [comment]
Hello Dr Gao,

Yes, I am need your help urgently.  The link will be expired on 4/2, could you please try it again?
![image](https://user-images.githubusercontent.com/37776318/229104952-eb5653ce-7e95-41a1-8a40-4cedecceaa7d.png)
https://filesender.renater.fr/?s=download&token=cb323bc2-a831-4df2-acbc-9dbf7b94246f

Best Wishes,
Jing

**Comment by YaqiangCao** [comment]
Hi JIng,
    I am downloading the data. What kind of data this is ?
Best,
Yaqiang

**Comment by poflawless** [comment]
Hello Dr Gao,
I don't really understand your question.

**Comment by YaqiangCao** [comment]
Hi JIng,
    I mean what kind of data are these? Hi-C? HiChIP? What is the highest
resolution?
        Regarding your parameters "-bs 1000,5000 -ws 500,1000,5000", it may
not totally make sense according to my experience of Hi-C or Hi-TrAC data.
-bs indicates the bin size for the matrix (resoltuion), and -ws indicates
the sliding window size, should be like 5/10/20 folds of the bin size.
    I have tested your data and if you removed those ctgxxx.ixy and
chrC-chrC.ixy, chrM-chrM.ixy, then run "cLoops2 update -d
Pre_sample1_merge_sampled", your parameters "cLoops2 callDomains -d
Pre_sample1_merge_sampled -o Pre_sample1_merge_sampled_Domain -bs 1000 -ws
5000,10000 -p 12" can be run without problem.
    What is the expecting size of the called domain if you visualize the
data in Juicer or Washu? I would like to suggest using
https://github.com/YaqiangCao/cLoops2/blob/master/scripts/getIS.py
(calculating insulation score) or
https://github.com/YaqiangCao/cLoops2/blob/master/scripts/getSS.py
(calculating segregation score as I proposed) to test a small chromosome to
optimize the parameters and then run the call Domains. Please also note,
the results are highly dependent on your parameters.
Best,
Yaqiang
